# Generated by Django 5.2.8 on 2025-11-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=256)),
                ('pinned', models.BooleanField(default=False)),
                ('contents', models.CharField(max_length=500)),
            ],
        ),
    ]
