# Generated by Django 5.2.8 on 2025-12-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cur_area',
            field=models.CharField(default='London', max_length=256),
            preserve_default=False,
        ),
    ]
