# Generated by Django 5.2.8 on 2025-12-01 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_cur_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 1, 2, 50, 49, 754611)),
            preserve_default=False,
        ),
    ]
